const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('snipPilot', {
  getInfo: () => ipcRenderer.invoke('app:get-info'),
  chooseStorageDir: () => ipcRenderer.invoke('app:choose-storage-dir'),
  updateConfig: (payload) => ipcRenderer.invoke('app:update-config', payload),
  quit: () => ipcRenderer.invoke('app:quit'),
  startSnip: () => ipcRenderer.invoke('app:start-snip'),
  startScrollSnip: () => ipcRenderer.invoke('app:start-scroll-snip'),
  onNewSnip: (callback) => ipcRenderer.on('editor:new-snip', (_event, payload) => callback(payload)),
  onOverlayCapture: (callback) => ipcRenderer.on('overlay:capture', (_event, payload) => callback(payload)),
  finishOverlaySnip: (payload) => ipcRenderer.send('overlay:snip', payload),
  finishScrollRegion: (payload) => ipcRenderer.send('overlay:scroll-region', payload),
  cancelOverlay: () => ipcRenderer.send('overlay:cancel'),
  captureScrollSegment: (direction) => ipcRenderer.invoke('scroll:capture-segment', direction),
  finishScrollCapture: () => ipcRenderer.invoke('scroll:finish'),
  cancelScrollCapture: () => ipcRenderer.invoke('scroll:cancel'),
  saveCapture: (payload) => ipcRenderer.invoke('capture:save', payload),
  copyImage: (dataUrl) => ipcRenderer.invoke('capture:copy-image', dataUrl),
  copyAgentPrompt: (payload) => ipcRenderer.invoke('capture:copy-agent-prompt', payload),
  listSnips: () => ipcRenderer.invoke('snips:list'),
  loadSnipImage: (filePath) => ipcRenderer.invoke('snips:load-image', filePath),
  copyPending: (id) => ipcRenderer.invoke('snips:copy-pending', id),
  copyImageByPath: (filePath) => ipcRenderer.invoke('snips:copy-image-by-path', filePath),
  savePending: (id) => ipcRenderer.invoke('snips:save-pending', id),
  discardPending: (id) => ipcRenderer.invoke('snips:discard-pending', id),
  updatePendingImage: (payload) => ipcRenderer.invoke('snips:update-pending-image', payload),
  openEditor: (payload) => ipcRenderer.invoke('snips:open-editor', payload),
  saveEditorImage: (payload) => ipcRenderer.invoke('editor:save-image', payload),
  finishEditor: (payload) => ipcRenderer.invoke('editor:finish', payload),
  closeEditor: () => ipcRenderer.invoke('editor:close'),
  openLibrary: () => ipcRenderer.invoke('snips:open-library'),
  openFolder: () => ipcRenderer.invoke('snips:open-folder'),
  onEditorInit: (callback) => ipcRenderer.on('editor:init', (_event, payload) => callback(payload)),
  onEditorFinishRequest: (callback) => ipcRenderer.on('editor:request-finish', () => callback()),
  onLibrarySnips: (callback) => ipcRenderer.on('library:snips', (_event, payload) => callback(payload)),
  onShelfSnips: (callback) => ipcRenderer.on('shelf:snips', (_event, payload) => callback(payload)),
  onConfig: (callback) => ipcRenderer.on('app:config', (_event, payload) => callback(payload)),
  onScrollFrameState: (callback) => ipcRenderer.on('scroll:state', (_event, payload) => callback(payload)),
  onStatus: (callback) => ipcRenderer.on('app:status', (_event, payload) => callback(payload))
});
